version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: beforeinstall.sh
      timeout: 60
      runas: root
  afterInstall:
    - location: afterinstall.sh
      timeout: 60
      runas: root
